### ISSUE TITLE
Are There Additional Self-Hosting Instructions?

### ISSUE THREAD

**Issue by mergesort** [videah/SkyBridge#65]
Hey @videah, I decided to spin up an instance of Skybridge on Fly using your instructions in the readme. I updated the fly.toml and docker-compose.yml below, and while it does deploy to Fly I'm not able to get Skybridge to do anything. (Visiting the instance's URL just tries to load up a webpage that never loads.)

fly.toml
```
app = 'obscured-for-privacy'
primary_region = 'ewr'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

```

Dockerfile
```
version: "3.8"
services:
  skybridge:
    container_name: "skybridge"
    image: videah/skybridge:latest
    restart: always
    volumes:
      - skybridge:/app/database
    environment:
      # Base URL of where SkyBridge will be hosted without the protocol.
      - SKYBRIDGE_BASEURL=obscured-for-privacy.fly.dev
      # Random secret, generate with `openssl rand -base64 32`.
      - SKYBRIDGE_SECRET
      # Password used to make a SkyBridge instance private.
      - SKYBRIDGE_AUTH_PASSWORD
      # Should a bridge password be required to authenticate?
      - SKYBRIDGE_REQUIRE_AUTH_PASSWORD=true
      # Should a nice index page be shown on the root URL?
      - SKYBRIDGE_SHOW_INDEX=false
      # Allow backfilling/scrolling on timelines? (can cause issues on instances under heavy load)
      - SKYBRIDGE_ALLOW_BACKFILL=true

volumes:
  skybridge:
```

Are there perhaps other dependencies or config changes I'd need to make to get a fresh instance running?

And of course, thank you so much for all the hard work!
